<a href="https://colab.research.google.com/github/Maruf-shiab/Deep-Learning/blob/main/Deep_learning_PerceptrOn_AND_Gate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import numpy as np

w=np.array([2,2])
x=np.array([2,2])
dot= np.dot(w,x)
dot

np.int64(8)

In [5]:
random=np.random.seed(42)
random

In [11]:
random_normal =np.random.randn(3)
random_normal

array([ 0.81644508, -1.523876  , -0.42804606])

In [12]:
import pandas as pd
data ={
    "X1" :[0,0,1,1],
    "X2" :[0,1,0,1],
    "Y" :[0,0,0,1],
}
AND =pd.DataFrame(data)
AND

   X1  X2  Y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [13]:
X= AND.drop("Y",axis=1)
X

   X1  X2
0   0   0
1   0   1
2   1   0
3   1   1

In [17]:
Y=AND['Y']
Y

0    0
1    0
2    0
3    1
Name: Y, dtype: int64

In [22]:
X.shape
len(X)

4

In [27]:
bias = -np.ones((len(X)))
bias =np.c_[X,bias]
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [28]:
class perceptron:
  def __init__(self,eta,epochs):
    self.weights =np.random.randn(3)*1e-4
    print(f"initial weights before training : \n{self.weights}")
    self.eta =eta
    self.epochs =epochs

  def activationFunction(self,inputs,weights):
    z=np.dot(inputs,weights)
    return np.where(z>0,1,0)

  def fit(self,X,Y):
    self.X=X
    self.Y=Y

    x_with_bias =np.c_[self.X,-np.ones(len(self.X))]

    print(f"x with bias : \n{x_with_bias}")

    for epoch in range(self.epochs):
      print("Epoch",epoch)
      y_hat=self.activationFunction(x_with_bias,self.weights)
      print(f"predicted value before training : \n{y_hat}")

      error=self.Y-y_hat
      print(f"error : \n{error}")

      #weight Update

      self.weights=self.weights+self.eta*np.dot(x_with_bias.T,error)
      print(f"updated weights after epoch : {epoch +1}/{self.epochs} : \n{self.weights}")



  def predict(self,X):
    x_with_bias=np.c_[x,-np.ones(len(X),1)]
    return self.activationFunction(x_with_bias,self.weights)

In [32]:
from ast import And
import pandas as pd
data ={
    "X1" :[0,0,1,1],
    "X2" :[0,1,0,1],
    "Y" :[0,0,0,1],
}
AND =pd.DataFrame(data)
AND
X=AND.drop("Y",axis=1)
Y=AND['Y']
Y

0    0
1    0
2    0
3    1
Name: Y, dtype: int64

In [33]:
model=perceptron(eta=0.01,epochs=10)
model.fit(X,Y)

initial weights before training :
[-7.42406837e-05 -7.03343802e-05 -2.13962066e-04]
x with bias :
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch 0
predicted value before training :
[1 1 1 1]
error :
0   -1
1   -1
2   -1
3    0
Name: Y, dtype: int64
updated weights after epoch : 1/10 :
[-0.01007424 -0.01007033  0.02978604]
Epoch 1
predicted value before training :
[0 0 0 0]
error :
0    0
1    0
2    0
3    1
Name: Y, dtype: int64
updated weights after epoch : 2/10 :
[-7.42406837e-05 -7.03343802e-05  1.97860379e-02]
Epoch 2
predicted value before training :
[0 0 0 0]
error :
0    0
1    0
2    0
3    1
Name: Y, dtype: int64
updated weights after epoch : 3/10 :
[0.00992576 0.00992967 0.00978604]
Epoch 3
predicted value before training :
[0 1 1 1]
error :
0    0
1   -1
2   -1
3    0
Name: Y, dtype: int64
updated weights after epoch : 4/10 :
[-7.42406837e-05 -7.03343802e-05  2.97860379e-02]
Epoch 4
predicted value before training :
[0 0 0 0]
error :
0    0
1    0
2    0
3    1
Name: Y, dtype: int64
updated weights after epoch : 5/10 :
[0.00992576 0.00992967 0.01978604]
Epoch 5
predicted value before training :
[0 0 0 1]
error :
0    0
1    0
2    0
3    0
Name: Y, dtype: int64
updated weights after epoch : 6/10 :
[0.00992576 0.00992967 0.01978604]
Epoch 6
predicted value before training :
[0 0 0 1]
error :
0    0
1    0
2    0
3    0
Name: Y, dtype: int64
updated weights after epoch : 7/10 :
[0.00992576 0.00992967 0.01978604]
Epoch 7
predicted value before training :
[0 0 0 1]
error :
0    0
1    0
2    0
3    0
Name: Y, dtype: int64
updated weights after epoch : 8/10 :
[0.00992576 0.00992967 0.01978604]
Epoch 8
predicted value before training :
[0 0 0 1]
error :
0    0
1    0
2    0
3    0
Name: Y, dtype: int64
updated weights after epoch : 9/10 :
[0.00992576 0.00992967 0.01978604]
Epoch 9
predicted value before training :
[0 0 0 1]
error :
0    0
1    0
2    0
3    0
Name: Y, dtype: int64
updated weights after epoch : 10/10 :
[0.00992576 0.00992967 0.01978604]